attendance/urls.py
from django.urls import path
from . import views


app_name = "attendance"
urlpatterns = [
    path("", views.home, name="home"),
    path("select/", views.attendance_select, name="attendance-select"),
    path("display/", views.attendance_display, name="attendance-display"),
    path("save/", views.attendance_save, name="attendance-save"),
    path("save-done/", views.attendance_save_done, name="attendance-save-done"),
    path(
        "attendance/<int:attendance_id>/",
        views.attendance_detail,
        name="attendance-detail",
    ),
    path(
        "attendance/<int:attendance_id>/change/",
        views.attendance_change,
        name="attendance-change",
    ),
    path(
        "attendance/<int:attendance_id>/delete/",
        views.attendance_delete,
        name="attendance-delete",
    ),
    path("attendance/", views.attendance_list_view, name="attendance-list"),
    path("grade/", views.grade_list_view, name="grade-list"),
    path("grade/add/", views.grade_add, name="grade-add"),
    path("grade/<int:grade_id>/change/", views.grade_change, name="grade-change"),
    path("grade/<int:grade_id>/delete/", views.grade_delete, name="grade-delete"),
    path("teacher/", views.teacher_list_view, name="teacher-list"),
    path("teacher/add/", views.teacher_add, name="teacher-add"),
    path("driver/", views.driver_list_view, name="driver-list"),
    path("driver/add/", views.driver_add, name="driver-add"),
    path(
        "teacher/<int:teacher_id>/change/", views.teacher_change, name="teacher-change"
    ),
    path(
        "teacher/<int:teacher_id>/password/",
        views.teacher_change_password,
        name="teacher-change-password",
    ),
    path("bus/", views.bus_list_view, name="bus-list"),
    path("bus/add/", views.bus_add, name="bus-add"),
    path("bus/<int:bus_id>/", views.bus_detail, name="bus-detail"),
    path("bus/<int:bus_id>/change/", views.bus_change, name="bus-change"),
    path("destination/", views.destination_list_view, name="destination-list"),
    path("destination/add/", views.destination_add, name="destination-add"),
    path(
        "destination/<int:destination_id>/",
        views.destination_detail,
        name="destination-detail",
    ),
    path(
        "destination/<int:destination_id>/change/",
        views.destination_change,
        name="destination-change",
    ),
    path("student/", views.student_list_view, name="student-list"),
    path("student/add/", views.student_add, name="student-add"),
    path("student/<int:student_id>/", views.student_detail, name="student-detail"),
    path(
        "student/<int:student_id>/change/", views.student_change, name="student-change"
    ),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("attendance/", include("attendance.urls")),
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
]

schoolbus/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("attendance/", include("attendance.urls")),
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
]

attendance/models.py
from django.db import models
from django.conf import settings


class School(models.Model):
    name = models.CharField(max_length=255)
    code = models.CharField(max_length=255, unique=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name

    # def get_absolute_url(self):
    #     return reverse("attendance:school-detail", kwargs={"pk": self.pk})


class Destination(models.Model):
    school = models.ForeignKey(School, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Bus(models.Model):
    school = models.ForeignKey(School, on_delete=models.CASCADE)
    # https://docs.djangoproject.com/en/4.1/ref/models/fields/#django.db.models.ForeignKey.limit_choices_to
    driver = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        limit_choices_to={"role": "DRIVER"},
        blank=True,
        null=True,
    )
    bus_number = models.CharField(max_length=255)
    capacity = models.IntegerField()
    plate = models.CharField(max_length=11)
    destinations = models.ManyToManyField(Destination)

    class Meta:
        verbose_name_plural = "busses"
        ordering = ["bus_number"]
        constraints = [
            models.UniqueConstraint(fields=["bus_number"], name="unique_bus_number")
        ]

    def __str__(self):
        return self.bus_number


class Grade(models.Model):
    school = models.ForeignKey(School, on_delete=models.CASCADE)
    level = models.CharField(max_length=255)
    branch = models.CharField(max_length=255)

    class Meta:
        ordering = ["level"]
        constraints = [
            models.UniqueConstraint(
                fields=["school", "level", "branch"],
                name="unique_grade_school_level_and_branch",
            )
        ]

    def __str__(self):
        return f"{self.level}/{self.branch}"


class Student(models.Model):
    school = models.ForeignKey(School, on_delete=models.CASCADE)
    bus = models.ForeignKey(Bus, on_delete=models.SET_NULL, null=True, blank=True)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    grade = models.ForeignKey(Grade, on_delete=models.CASCADE)

    class Meta:
        ordering = ["first_name"]

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Attendance(models.Model):
    DIRECTION_CHOICES = (
        ("COMING", "COMING"),
        ("LEAVING", "LEAVING"),
    )
    school = models.ForeignKey(School, on_delete=models.CASCADE)
    bus = models.ForeignKey(Bus, on_delete=models.CASCADE)
    check_date = models.DateField()
    direction = models.CharField(max_length=7, choices=DIRECTION_CHOICES)
    teacher = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    signed_at = models.DateTimeField(auto_now=True)
    is_signed = models.BooleanField(default=False)

    class Meta:
        ordering = ["-check_date"]
        constraints = [
            models.UniqueConstraint(
                fields=["school", "bus", "check_date", "direction"],
                name="unique_attendance_with_school_bus_date_and_direction",
            )
        ]

    def __str__(self):
        return (
            f"{self.school.name} | {self.bus} | {self.check_date} | {self.direction} | "
            f"{self.teacher} | {self.is_signed}"
        )

    # def get_absolute_url(self):
    #     return reverse("attendance-detail", kwargs={"pk": self.pk})


class StudentAttendance(models.Model):
    attendance = models.ForeignKey(Attendance, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    present = models.BooleanField(default=False)

    class Meta:
        ordering = ["-attendance"]
        constraints = [
            models.UniqueConstraint(
                fields=["attendance", "student"],
                name="unique_student_with_student_and_attendance",
            )
        ]

    def __str__(self):
        return f"Attendance: {self.attendance.id} | Student: {self.student} | Present: {self.present}"

attendance/views.py
import datetime

from django.http import Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.decorators import permission_required

from .models import (
    School,
    Bus,
    Student,
    StudentAttendance,
    Attendance,
    Grade,
    Destination,
)


def user_role_check(user):
    # Checks user has ADMIN or MANAGER role for doing sensitive process
    return user.role == "ADMIN" or user.role == "MANAGER"


def home(request):
    return render(request, "attendance/home.html")


@login_required
def attendance_select(request):
    bus_list = Bus.objects.filter(school=request.user.school)
    context = {"bus_list": bus_list, "today": datetime.date.today()}
    return render(request, "attendance/attendance_select.html", context)


@login_required
def attendance_display(request):
    bus = get_object_or_404(
        Bus.objects.filter(school=request.user.school), id=request.POST.get("bus")
    )
    check_date = request.POST.get("check_date")
    direction = request.POST.get("direction", "COMING")
    check_date = datetime.datetime.strptime(check_date, "%Y-%m-%d").date()

    # Get or create new attendance
    attendance, created = Attendance.objects.get_or_create(
        school=request.user.school,
        bus=bus,
        direction=direction,
        check_date=check_date,
        defaults={"teacher": request.user},
    )

    request.session["attendance_id"] = attendance.id
    request.session["bus_id"] = bus.id

    context = {
        "attendance": attendance,
    }

    if attendance.is_signed:
        studentattendance_list = StudentAttendance.objects.filter(attendance=attendance)
        context["studentattendance_list"] = studentattendance_list
        return render(request, "attendance/attendance_display_exist.html", context)
    else:
        student_list = Student.objects.filter(school=request.user.school, bus=bus)
        context["student_list"] = student_list
        return render(request, "attendance/attendance_display_new.html", context)


@login_required
def attendance_save(request):
    """Save attendance logic"""
    if request.method == "POST":
        student_list = Student.objects.filter(
            school=request.user.school, bus=request.session["bus_id"]
        )
        present_list = request.POST.getlist("present_list")

        # Delete all attendance for attendance
        attendance = get_object_or_404(
            Attendance.objects.filter(school=request.user.school),
            id=request.session.get("attendance_id"),
        )
        # Delete StudentAttendance list if already signed
        if attendance.is_signed:
            StudentAttendance.objects.filter(attendance=attendance).delete()

        # Create student attendance records
        for student in student_list:
            StudentAttendance.objects.create(
                attendance=attendance,
                student=student,
                present=str(student.id) in present_list,
            )

        # Touch Attendance Model for update to signed_at field
        attendance.is_signed = True
        attendance.teacher = request.user
        attendance.save()

        # return redirect("attendance:attendance-detail", attendance.id)
        return redirect("attendance:attendance-save-done")


@login_required
def attendance_save_done(request):
    """Render save done template"""
    attendance = get_object_or_404(
        Attendance.objects.filter(school=request.user.school),
        id=request.session.get("attendance_id"),
    )
    del request.session["attendance_id"]
    context = {"attendance": attendance}
    return render(request, "attendance/attendance_save_done.html", context)


@login_required
def attendance_detail(request, attendance_id):
    attendance = get_object_or_404(
        Attendance.objects.filter(school=request.user.school), id=attendance_id
    )
    context = {"attendance": attendance}
    return render(request, "attendance/attendance_detail.html", context)


@login_required
def attendance_list_view(request):
    attendance_list = Attendance.objects.filter(school=request.user.school)
    context = {
        "attendance_list": attendance_list,
    }
    return render(request, "attendance/attendance_list.html", context)


@login_required
def attendance_change(request, attendance_id):
    attendance = get_object_or_404(
        Attendance.objects.filter(school=request.user.school), id=attendance_id
    )
    studentattendance_list = StudentAttendance.objects.filter(attendance=attendance)

    request.session["attendance_id"] = attendance.id
    context = {
        "studentattendance_list": studentattendance_list,
        "attendance": attendance,
    }
    return render(request, "attendance/attendance_change.html", context)


@login_required
@user_passes_test(user_role_check)
def attendance_delete(request, attendance_id):
    attendance = get_object_or_404(
        Attendance.objects.filter(school=request.user.school), id=attendance_id
    )

    if request.method == "POST":
        attendance.delete()
        return redirect("attendance:attendance-list")

    context = {"attendance": attendance}
    return render(request, "attendance/attendance_delete.html", context)


@login_required
def grade_list_view(request):
    grade_list = Grade.objects.filter(school=request.user.school)
    context = {
        "grade_list": grade_list,
    }
    return render(request, "attendance/grade_list.html", context)


@login_required
def grade_add(request):
    if request.method == "POST":
        school = request.user.school
        level = request.POST["level"]
        branch = request.POST["branch"]

        grade = Grade(school=school, level=level, branch=branch)
        grade.save()
        return redirect("attendance:home")

    return render(request, "attendance/grade_add.html")


@login_required
def grade_change(request, grade_id):
    grade = get_object_or_404(
        Grade.objects.filter(school=request.user.school), id=grade_id
    )

    if request.method == "POST":
        level = request.POST["level"]
        branch = request.POST["branch"]

        grade.level = level
        grade.branch = branch
        try:
            grade.save()
        except Exception as e:
            raise Http404("Update error.")

        return redirect("attendance:grade-list")

    context = {"grade": grade}
    return render(request, "attendance/grade_change.html", context)


@login_required
def grade_delete(request, grade_id):
    grade = get_object_or_404(
        Grade.objects.filter(school=request.user.school), id=grade_id
    )

    if request.method == "POST":
        grade.delete()
        return redirect("attendance:grade-list")

    context = {"grade": grade}
    return render(request, "attendance/grade_delete.html", context)


@login_required
def driver_add(request):
    if request.method == "POST":
        try:
            get_user_model().objects.create_user(
                school=request.user.school,
                role="DRIVER",
                username=request.POST["username"],
                first_name=request.POST["first_name"],
                last_name=request.POST["last_name"],
                email=request.POST["email"],
                password=request.POST["password"],
            )
        except Exception as e:
            raise Http404("User creation error.")

        return redirect("attendance:driver-list")

    return render(request, "attendance/driver_add.html")


@login_required
def driver_list_view(request):
    driver_list = get_user_model().objects.filter(
        school=request.user.school, role="DRIVER"
    )
    context = {
        "driver_list": driver_list,
    }
    return render(request, "attendance/driver_list.html", context)


@login_required
def teacher_list_view(request):
    teacher_list = get_user_model().objects.filter(
        school=request.user.school, role="TEACHER"
    )
    context = {
        "teacher_list": teacher_list,
    }
    return render(request, "attendance/teacher_list.html", context)


@login_required
def teacher_add(request):
    if request.method == "POST":
        school = request.user.school
        username = request.POST["username"]
        first_name = request.POST["first_name"]
        last_name = request.POST["last_name"]
        email = request.POST["email"]
        password = request.POST["password"]

        try:
            get_user_model().objects.create_user(
                school=school,
                role="TEACHER",
                username=username,
                first_name=first_name,
                last_name=last_name,
                email=email,
                password=password,
            )
        except Exception as e:
            raise Http404("User creation error.")

        return redirect("attendance:teacher-list")

    return render(request, "attendance/teacher_add.html")


@login_required
def teacher_change(request, teacher_id):
    teacher = get_object_or_404(
        get_user_model().objects.filter(school=request.user.school), id=teacher_id
    )

    if request.method == "POST":
        username = request.POST["username"]
        first_name = request.POST["first_name"]
        last_name = request.POST["last_name"]
        email = request.POST["email"]

        teacher.username = username
        teacher.first_name = first_name
        teacher.last_name = last_name
        teacher.email = email

        try:
            teacher.save()
        except Exception as e:
            raise Http404("Teacher update error.")

        return redirect("attendance:teacher-list")

    context = {
        "teacher": teacher,
    }
    return render(request, "attendance/teacher_change.html", context)


@login_required
def teacher_change_password(request, teacher_id):

attendance/templates/attendance/attendance_choose.html
{% extends "base.html" %}

{% block title %}Attendance Choose{% endblock title %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}! You are at {{ user.role }} role. -> <a href="{% url 'logout' %}">Log Out</a>
  <p></p>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">Log In</a> |
  <a href="{% url 'signup' %}">Sign Up</a>
{% endif %}
<h1>Attendance Choose</h1>
<form method="post" action="{% url 'attendance:attendance-display' %}">{% csrf_token %}
    Bus:
    <select name="bus" required id="bus">
        <option value selected>-----</option>
        {% for bus in bus_list %}
            <option value="{{ bus.id }}">{{ bus.bus_number }}</option>
        {% endfor %}
    </select>

    <label for="check_date">Date:</label>
    <input type="date" id="check_date" name="check_date" value="{{ today|date:'Y-m-d' }}"><br>
    Direction:
    <input type="radio" id="coming" name="direction" value="COMING">
    <label for="coming">Coming</label>
    <input type="radio" id="leaving" name="direction" value="LEAVING">
    <label for="leaving">Leaving</label><br>

    <input type="submit" value="Get attendance">
</form>

<p><a href="{% url 'attendance:home' %}">Home page</a></p>
{% endblock content %}

attendance/templates/attendance/attendance_detail.html
{% extends "base.html" %}

{% block title %}Attendance Detail{% endblock title %}

{% block content %}
<h1>{{ attendance }}</h1>

<h2>Attendance:</h2>

  Status | Full Name <br>
  {% for studentattendance in attendance.studentattendance_set.all %}
    <div class="form-check form-switch">
      <input class="form-check-input" type="checkbox" role="switch" id="student{{ forloop.counter }}" name="present_list"
             value="{{ studentattendance.student.id }}" {% if studentattendance.present %} checked{% endif %} disabled>
      <label class="form-check-label" for="student{{ forloop.counter }}">{{ studentattendance.student }}</label>
    </div>
  {% empty %}
    <p>Sorry, no students in this list.</p>
  {% endfor %}

<a href="{% url 'attendance:attendance-change' attendance.id %}">Change</a> |
<a href="{% url 'attendance:attendance-delete' attendance.id %}">DELETE</a>
<br>
<a href="{% url 'attendance:attendance-select' %}">Get new attendance</a>

{% endblock content %}

attendance/templates/attendance/attendance_display_exist.html
{% extends "base.html" %}

{% block title %}Attendance get{% endblock title %}

{% block content %}
<h1>Bus {{ attendance.bus }} (Exist)</h1>
<p>Attendance: {{ attendance }}</p>
<form method="post" action="{% url 'attendance:attendance-save' %}">
  {% csrf_token %}
  Status | Full Name <br>
  {% for studentattendance in studentattendance_list %}
    <div class="form-check form-switch">
      <input class="form-check-input" type="checkbox" role="switch" id="student{{ forloop.counter }}" name="present_list"
             value="{{ studentattendance.student.id }}" {% if studentattendance.present %} checked{% endif %}>
      <label class="form-check-label" for="student{{ forloop.counter }}">{{ studentattendance.student }}</label>
    </div>
  {% empty %}
    <p>Sorry, no students in this list.</p>
  {% endfor %}
  <input type="submit" value="Save">
</form>

{% endblock content %}

attendance/templates/attendance/attendance_list.html
{% extends "base.html" %}

{% block title %}Attendance List{% endblock title %}

{% block content %}
<h1>Attendance List</h1>
<p><a href="{% url 'attendance:attendance-select' %}" class="btn btn-primary">Add Attendance +</a></p>
<table class="table table-striped table-bordered">
  <thead>
  <tr>
    <th>School</th>
    <th>Bus number</th>
    <th>Date</th>
    <th>Direction</th>
    <th>Teacher</th>
    <th>Signed</th>
    <th>Signed</th>
  </tr>
  </thead>
  <tbody>
    {% for attendance in attendance_list %}
    <tr>
      <td>{{ attendance.school }}</td>
      <td>{{ attendance.bus }}</td>
      <td>{{ attendance.check_date }}</td>
      <td>{{ attendance.direction }}</td>
      <td>{{ attendance.teacher }}</td>
      <td>{{ attendance.is_signed }}</td>
      <td><a href="{% url 'attendance:attendance-detail' attendance.id %}"> detail </a>
    | <a href="{% url 'attendance:attendance-change' attendance.id %}"> change </a>
    | <a href="{% url 'attendance:attendance-delete' attendance.id %}"> delete </a></td>
    </tr>
    {% empty %}
    <p>No attendances are available.</p>
    {% endfor %}
  </tbody>
</table>

{% endblock content %}

attendance/templates/attendance/attendance_select.html
{% extends "base.html" %}

{% block title %}Attendance Choose{% endblock title %}

{% block content %}
<h1>Attendance Choose</h1>
<form method="post" action="{% url 'attendance:attendance-display' %}">{% csrf_token %}
  <label for="check_date">Date:</label>
  <input type="date" id="check_date" name="check_date" value="{{ today|date:'Y-m-d' }}">
  <input type="radio" id="coming" name="direction" value="COMING" required>
  <label for="coming">Coming</label>
  <input type="radio" id="leaving" name="direction" value="LEAVING" required>
  <label for="leaving">Leaving</label><br><br>
  Bus:
  <select name="bus" required id="bus">
    <option value selected>-----</option>
    {% for bus in bus_list %}
    <option value="{{ bus.id }}">{{ bus.bus_number }}</option>
    {% endfor %}
  </select>
  <input type="submit" value="Get attendance">
</form>

<p><a href="{% url 'attendance:home' %}">Home page</a></p>
{% endblock content %}

attendance/templates/attendance/bus_add.html
{% extends "base.html" %}

{% block title %}Bus Add{% endblock title %}

{% block content %}

<h1>Bus Add</h1>

<form action="" method="post">
    {% csrf_token %}
    Driver:
    <select name="driver" required id="driver">
        <option value selected>-----</option>
        {% for driver in driver_list %}
            <option value="{{ driver.id }}" {% if driver.id == bus.driver_id %} selected{% endif %}>{{ driver }}</option>
        {% endfor %}
    </select><br>
    Bus_number:<br>
    <input name="bus_number"}">
    <br><br>
    Capacity:<br>
    <input type="number" name="capacity"">
    <br><br>
    Plate:<br>
    <input name="plate"">
    <br><br>
    <label for="destinations">Destinations:</label>
    <select name="destinations" id="destinations" multiple>
        {% for destination in destination_list %}
            <option value="{{ destination.id }} {% if destination in bus.destination.all %}selected{% endif %}">{{ destination }}</option>
        {% endfor %}
    </select>
    <br><br>
    <input type="submit" value="SAVE">
</form>

{% endblock content %}

attendance/templates/attendance/bus_detail.html
{% extends "base.html" %}

{% block title %}Bus Detail{% endblock title %}

{% block content %}
<h2>Bus {{bus}} Detail:</h2>
School: {{ bus.school }}<br>
Driver: {{ bus.driver }}<br>
Bus_number: {{ bus.bus_number }}<br>
Capacity: {{ bus.capacity }}<br>
Plate: {{ bus.plate }}<br>
Destinations: {% for destination in bus.destinations.all %} {{ destination }}, {% endfor %}<br>

<ul>
  {% for student in bus.student_set.all %}
  <li>{{ student }}</li>
  {% empty %}
  <li>There is no student on this bus.</li>
  {% endfor %}
</ul>

<a href="{% url 'attendance:bus-change' bus.id %}">Change</a>
<br>
<a href="{% url 'attendance:bus-list' %}">Bus List</a>

{% endblock content %}

attendance/templates/attendance/destination_add.html
{% extends "base.html" %}

{% block title %}Destination Grade{% endblock title %}

{% block content %}

<h1>Destination Grade</h1>

<form action="" method="post">
  {% csrf_token %}
  Name:<br>
  <input name="name">
  <br><br>
  <input type="submit" value="SAVE">
</form>

{% endblock content %}

attendance/templates/attendance/destination_list.html
{% extends "base.html" %}

{% block title %}Destination List{% endblock title %}

{% block content %}
<h1>Destination List</h1>
<p>Destination Add -> <a href="{% url 'attendance:destination-add' %}">+ Add destination</a></p>

<ul>
{% for destination in destination_list %}
    <li>{{ destination.name }} | <a href="{% url 'attendance:destination-change' destination.id %}">edit</a>
     | <a href="{% url 'attendance:destination-detail' destination.id %}">delete</a></li>
{% empty %}
    <li>Sorry, no destination in this list.</li>
{% endfor %}
</ul>
{% endblock content %}

attendance/templates/attendance/grade_change.html
{% extends "base.html" %}

{% block title %}Grade Change{% endblock title %}

{% block content %}

<h1>Change Grade</h1>

<form action="" method="post">
  {% csrf_token %}
  Level:<br>
  <input name="level" value="{{ grade.level }}">
  <br><br>
  Branch:<br>
  <input name="branch" value="{{ grade.branch }}">
  <br><br>
  <input type="submit" value="SAVE">
</form>

{% endblock content %}

attendance/templates/attendance/grade_delete.html
{% extends "base.html" %}

{% block content %}
<h1>Grade Delete</h1>
<form action="" method="post">{% csrf_token %}
  <p>Are you sure you want to delete "{{ grade }}"?</p>
  <input type="submit" value="Confirm">
</form>
{% endblock content %}

attendance/templates/attendance/student_add.html
{% extends "base.html" %}

{% block title %}Student Add{% endblock title %}

{% block content %}

<h1>Add Student</h1>

<form action="" method="post">
  {% csrf_token %}
  First name:<br>
  <input name="first_name" required>
  <br><br>
  Last name:<br>
  <input name="last_name" required>
  <br><br>
  Grade:
  <select name="grade" id="grade" required>
    <option value selected>-----</option>
    {% for grade in grade_list %}
    <option value="{{ grade.id }}">{{ grade }}</option>
    {% endfor %}
  </select><br>
  Bus:
  <select name="bus" id="bus">
    <option value="" selected>-----</option>
    {% for bus in bus_list %}
    <option value="{{ bus.id }}">{{ bus }}</option>
    {% endfor %}
  </select><br>
  <input type="submit" value="SAVE">
</form>

{% endblock content %}

attendance/templates/attendance/student_change.html
{% extends "base.html" %}

{% block title %}Student Change{% endblock title %}

{% block content %}

<h1>Student Change</h1>

<form action="" method="post">
  {% csrf_token %}
  First name:<br>
  <input name="first_name" value="{{ student.first_name }}">
  <br><br>
  Last name:<br>
  <input name="last_name" value="{{ student.last_name }}">
  <br><br>
  Grade:
  <select name="grade" id="grade" required>
    <option value selected>-----</option>
    {% for grade in grade_list %}
    <option value="{{ grade.id }}" {% if grade.id == student.grade_id %} selected{% endif %}>{{ grade }}</option>
    {% endfor %}
  </select><br>
  Bus:
  <select name="bus" id="bus" required>
    <option value selected>-----</option>
    {% for bus in bus_list %}
    <option value="{{ bus.id }}" {% if bus.id == student.bus_id %} selected{% endif %}>{{ bus }}</option>
    {% endfor %}
  </select><br>
  <input type="submit" value="SAVE">
</form>

{% endblock content %}

attendance/templates/attendance/teacher_change.html
{% extends "base.html" %}

{% block title %}Teacher Change{% endblock title %}

{% block content %}

<h1>Teacher Change</h1>

<form action="" method="post">
  {% csrf_token %}
  Username:<br>
  <input name="username" value="{{ teacher.username }}">
  <br><br>
  First name:<br>
  <input name="first_name" value="{{ teacher.first_name }}">
  <br><br>
  Last name:<br>
  <input name="last_name" value="{{ teacher.last_name }}">
  <br><br>
  Email:<br>
  <input name="email" value="{{ teacher.email }}">
  <br><br>
  Role:<br>
  <input value="{{ teacher.role }}" disabled>
  <br><br>
  <p><a href="{% url 'attendance:teacher-change-password' teacher.id %}">Password Change</a></p>
  <input type="submit" value="SAVE">
</form>

{% endblock content %}