attendance/urls.py
from django.urls import path
from . import views


app_name = "attendance"
urlpatterns = [
    path("", views.home, name="home"),
    path("select/", views.attendance_select, name="attendance-select"),
    path("display/", views.attendance_display, name="attendance-display"),
    path("save/", views.attendance_save, name="attendance-save"),
    path("save-done/", views.attendance_save_done, name="attendance-save-done"),
    path(
        "attendance/<int:attendance_id>/",
        views.attendance_detail,
        name="attendance-detail",
    ),
    path(
        "attendance/<int:attendance_id>/change/",
        views.attendance_change,
        name="attendance-change",
    ),
    path(
        "attendance/<int:attendance_id>/delete/",
        views.attendance_delete,
        name="attendance-delete",
    ),
    path("attendance/", views.attendance_list_view, name="attendance-list"),
    path("grade/", views.grade_list_view, name="grade-list"),
    path("grade/add/", views.grade_add, name="grade-add"),
    path("grade/<int:grade_id>/change/", views.grade_change, name="grade-change"),
    path("grade/<int:grade_id>/delete/", views.grade_delete, name="grade-delete"),
    path("teacher/", views.teacher_list_view, name="teacher-list"),
    path("teacher/add/", views.teacher_add, name="teacher-add"),
    path("driver/", views.driver_list_view, name="driver-list"),
    path("driver/add/", views.driver_add, name="driver-add"),
    path(
        "teacher/<int:teacher_id>/change/", views.teacher_change, name="teacher-change"
    ),
    path(
        "teacher/<int:teacher_id>/password/",
        views.teacher_change_password,
        name="teacher-change-password",
    ),
    path("bus/", views.bus_list_view, name="bus-list"),
    path("bus/add/", views.bus_add, name="bus-add"),
    path("bus/<int:bus_id>/", views.bus_detail, name="bus-detail"),
    path("bus/<int:bus_id>/change/", views.bus_change, name="bus-change"),
    path("destination/", views.destination_list_view, name="destination-list"),
    path("destination/add/", views.destination_add, name="destination-add"),
    path(
        "destination/<int:destination_id>/",
        views.destination_detail,
        name="destination-detail",
    ),
    path(
        "destination/<int:destination_id>/change/",
        views.destination_change,
        name="destination-change",
    ),
    path("student/", views.student_list_view, name="student-list"),
    path("student/add/", views.student_add, name="student-add"),
    path("student/<int:student_id>/", views.student_detail, name="student-detail"),
    path(
        "student/<int:student_id>/change/", views.student_change, name="student-change"
    ),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("attendance/", include("attendance.urls")),
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
]

schoolbus/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("attendance/", include("attendance.urls")),
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
]

templates/base.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}School Bus Attendance App{% endblock title %}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>
<body>
<header class="p-5 bg-primary text-white text-center">
  <h1>School Bus Service Attendance</h1>
  <p>Use this app free!</p>
</header>

<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home' %}">OHA</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'attendance:attendance-list' %}">Attendances</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'attendance:grade-list' %}">Grades</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'attendance:teacher-list' %}">Teachers</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'attendance:driver-list' %}">Drivers</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'attendance:bus-list' %}">Busses</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'attendance:destination-list' %}">Destinations</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'attendance:student-list' %}">Students</a>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link disabled" href="#">{{ user }}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'signup' %}">Signup</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <main>
    {% block content %}
    {% endblock content %}
  </main>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
        crossorigin="anonymous"></script>
</body>
</html>

templates/base2.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Bookstore{% endblock title %}</title>
  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <!-- CSS -->

</head>
<body>
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home' %}">Bookstore</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'attendance:home' %}">About</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Log In</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'signup' %}">Sign Up</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    {% block content %}
    {% endblock content %}
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  <!-- JavaScript -->

</body>
</html>

templates/base3.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Newspaper App{% endblock title %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>
<body>
  <div class="container">
    <header class="p-3 mb-3 border-bottom">
      <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center
          justify-content-lg-start">
          <a class="navbar-brand" href="{% url 'home' %}">Newspaper</a>
          <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center
            mb-md-0">
          {% if user.is_authenticated %}
            <li><a href="#" class="nav-link px-2 link-dark">+ New</a></li>
          </ul>
          <div class="dropdown text-end">
            <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle"
              id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
              {{ user.username }}
            </a>
            <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
              <li><a class="dropdown-item" href="{% url 'password_change'%}">
                Change password</a></li>
              <li><a class="dropdown-item" href="{% url 'logout' %}">Log Out</a></li>
            </ul>
          </div>
          {% else %}
          <div class="text-end">
            <a href="{% url 'login' %}" class="btn btn-outline-primary me-2">Log In</a>
            <a href="{% url 'signup' %}" class="btn btn-primary">Sign Up</a>
          </div>
          {% endif %}
        </div>
      </div>
    </header>

    <main>
      {% block content %}
      {% endblock content %}
    </main>
  </div>

  <!-- Bootstrap JavaScript Bundle -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>
</html>

templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock title %}

{% block content %}
  <div class="mt-4 p-5 bg-primary text-white rounded text-center">
    <h1>To start press button</h1>
    <a href="{% url 'attendance:home' %}" class="btn btn-success">Go to Attendance</a>
  </div>
{% endblock content %}